# Generated by Django 3.2 on 2021-04-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiRest', '0002_auto_20210427_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='tag',
            field=models.CharField(choices=[('BUG', 'BUG'), ('AMELIORATION', 'AMÉLIORATION'), ('TACHE', 'TÂCHE')], default='TACHE', max_length=15),
        ),
    ]
